# Generated by Django 4.0.1 on 2022-02-24 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0014_alter_pokemon_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='raridade',
            field=models.TextField(default='comun', max_length=10),
        ),
    ]
