# Generated by Django 4.0.1 on 2022-02-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0012_alter_pokemon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='image_name',
            field=models.TextField(default=models.TextField(max_length=50), max_length=50),
        ),
    ]
